// tailwind-config.js

tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#0d1a38",
        "surface-container-high": "#e7e8e9",
        "on-error-container": "#93000a",
        "surface-tint": "#5c47d0",
        "on-secondary-container": "#144f84",
        "surface-bright": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "secondary-container": "#92c1fe",
        "on-tertiary-container": "#a1add2",
        "on-background": "#191c1d",
        "inverse-surface": "#2e3132",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#a0c9ff",
        "surface-container": "#edeeef",
        "surface-dim": "#d9dadb",
        primary: "#280091",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#bac6ec",
        "tertiary-fixed": "#dae2ff",
        "on-primary-fixed-variant": "#4329b7",
        "on-primary-container": "#aea3ff",
        "on-secondary": "#ffffff",
        surface: "#f8f9fa",
        tertiary: "#1f2b49",
        secondary: "#2d6197",
        "on-tertiary-fixed-variant": "#3a4666",
        outline: "#787585",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e5deff",
        "inverse-primary": "#c8bfff",
        "outline-variant": "#c9c4d6",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-container": "#354160",
        background: "#f8f9fa",
        "primary-container": "#3e22b2",
        "on-surface-variant": "#474554",
        "secondary-fixed": "#d2e4ff",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c8bfff",
        "on-primary-fixed": "#190064",
        "on-secondary-fixed-variant": "#07497d",
        "on-secondary-fixed": "#001c37",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Manrope"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
};
